cluster:
  name: "LocalFSCluster"
  storage:
    type: "hadoop"
    uri: "file:///"
    root-path: "/tmp/openhouse"
  iceberg:
    write:
      format:
        default: "orc"
      metadata:
        previous-versions-max: 28
        delete-after-commit:
          enabled: true
  housetables:
    base-uri: "http://openhouse-housetables:8080"
    database:
      type: "IN_MEMORY"
  security:
    token:
      interceptor:
        classname: "com.linkedin.openhouse.common.security.KeyCloakTokenInterceptor"
    tables:
      authorization:
        enabled: true
        opa:
          base-uri: "http://opa:8181"